export const templates = {
    tasks: {
        blank: { name: 'Blank Project', columns: [{id: 'todo', title: 'To Do'}, {id: 'inprogress', title: 'In Progress'}, {id: 'done', title: 'Done'}], items: [] },
        kanban: { name: 'Standard Kanban', columns: [{id: 'backlog', title: 'Backlog'}, {id: 'todo', title: 'To Do'}, {id: 'inprogress', title: 'In Progress'}, {id: 'done', title: 'Done'}], items: [ { title: 'Review project requirements', priority: 'high', status: 'backlog' }, { title: 'Set up development environment', priority: 'medium', status: 'todo' }, ] },
        honeydo: { name: 'Honey-Do List', columns: [{id: 'todo', title: 'To Do'}, {id: 'doing', title: 'Doing'}, {id: 'done', title: 'Done'}], items: [ { title: 'Fix leaky faucet in kitchen', priority: 'high', status: 'todo' }, { title: 'Mow the lawn', priority: 'medium', status: 'todo' }, { title: 'Clean out the garage', priority: 'low', status: 'todo' }, { title: 'Paint the guest bedroom', priority: 'medium', status: 'todo' }, ] },
        appdev: { name: 'App Planning', columns: [{id: 'backlog', title: 'Backlog'}, {id: 'design', title: 'Design'}, {id: 'development', title: 'Development'}, {id: 'testing', title: 'Testing'}, {id: 'deployed', title: 'Deployed'}], items: [ { title: 'User authentication flow', priority: 'high', status: 'backlog' }, { title: 'Design database schema', priority: 'high', status: 'design' }, { title: 'Develop API endpoints', priority: 'medium', status: 'development' }, { title: 'Write unit tests for login', priority: 'medium', status: 'testing' }, ] },
        event: { name: 'Event Planning', columns: [{ id: 'planning', title: 'Planning'}, {id: 'booking', title: 'Booking'}, {id: 'preparations', title: 'Preparations'}, {id: 'complete', title: 'Complete'}], items: [ { title: 'Finalize Guest List', priority: 'high', status: 'planning' }, { title: 'Book Venue', priority: 'high', status: 'booking' }, { title: 'Hire Caterer', priority: 'high', status: 'booking' }, { title: 'Send out invitations', priority: 'medium', status: 'preparations' }, ] }
    },
    'reserve-study': {
        blank: { name: 'Blank Project', columns: [{id: 'kickoff', title: 'Kick-off'}, {id: 'datacollection', title: 'Data Collection'}, {id: 'analysis', title: 'Analysis'}, {id: 'reporting', title: 'Reporting'}, {id: 'review', title: 'Review'}], items: [] },
        process: { name: 'Reserve Study Process', columns: [{id: 'kickoff', title: 'Kick-off & Proposal'}, {id: 'datacollection', title: 'Data Collection'}, {id: 'analysis', title: 'Analysis & Reporting'}, {id: 'review', title: 'Internal & Client Review'}, {id: 'final', title: 'Final Submittal'}], items: [  { title: 'Client Kick-off Meeting', priority: 'high', status: 'kickoff'}, { title: 'Proposal Submission & Approval', priority: 'high', status: 'kickoff'}, { title: 'On-site Data Collection', priority: 'high', status: 'datacollection'}, { title: 'Component Condition Assessment', priority: 'high', status: 'datacollection'}, { title: 'Draft Financial Analysis', priority: 'medium', status: 'analysis'}, { title: 'Generate Draft Report', priority: 'medium', status: 'analysis'}, { title: 'Internal QA/QC Review', priority: 'high', status: 'review'}, { title: 'Submit Final Report to Client', priority: 'high', status: 'final'}, ] },
    }
};